-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 21:47:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbtodolist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbtodolist` ;

-- -----------------------------------------------------
-- Schema dbtodolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtodolist` DEFAULT CHARACTER SET utf8 ;
USE `dbtodolist` ;

-- -----------------------------------------------------
-- Table `dbtodolist`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtodolist`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `state` TINYINT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
